### ISSUE TITLE
Upgrade dependency libraries

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#107]
- [x] jquery
- [ ] lodash.js
- [ ] bootstrap
- [x] algoliasearch
- [x] bootswatch 
- [x] clipboard.js
- [ ] handlebars.js
- [ ] highlight.js

**Comment by PeterDaveHello** [comment]
* b5262d0 upgrade algoliasearch client v2.8.0 -> v3.10.2 
* 82eab3f upgrade bootswatch from v3.3.4 to v3.3.6
* e0e9317 upgrade jquery from v1.7.2 to v1.12.0

**Comment by PeterDaveHello** [comment]
*  f5c5aa2 upgrade lodash from ^3.10 to ^4.5

**Comment by PeterDaveHello** [comment]
The upgrade of lodash makes the api crashed in heroku, but I have no problem with my local env.
cc @cdnjs/website @cdnjs/team-cdnjs 
```
Feb 21 01:07:29 cdnjsapi heroku/api:  Deploy 6f52bdb by hsu@peterdavehello.org 
Feb 21 01:07:29 cdnjsapi heroku/api:  Release v1107 created by hsu@peterdavehello.org 
Feb 21 01:07:29 cdnjsapi heroku/slug-compiler:  Slug compilation started 
Feb 21 01:07:29 cdnjsapi heroku/web.1:  Restarting 
Feb 21 01:07:29 cdnjsapi heroku/slug-compiler:  Slug compilation finished 
Feb 21 01:07:29 cdnjsapi heroku/web.1:  State changed from up to starting 
Feb 21 01:07:33 cdnjsapi heroku/web.1:  Stopping all processes with SIGTERM 
Feb 21 01:07:33 cdnjsapi heroku/web.1:  Starting process with command `./runServer.sh` 
Feb 21 01:07:34 cdnjsapi heroku/web.1:  Process exited with status 143 
Feb 21 01:07:35 cdnjsapi app/web.1:  {"v":0,"level":30,"name":"newrelic","hostname":"132e6ccd-4127-49b0-9f30-ece3791c987d","pid":6,"time":"2016-02-21T09:07:35.600Z","msg":"Starting New Relic for Node.js connection process."} 
Feb 21 01:07:36 cdnjsapi app/web.1:  Sun, 21 Feb 2016 09:07:35 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at apiServer.js:18:9 
Feb 21 01:07:36 cdnjsapi app/web.1:  Sun, 21 Feb 2016 09:07:35 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body-parser/index.js:105:29 
Feb 21 01:07:39 cdnjsapi app/web.1:  module.js:327 
Feb 21 01:07:39 cdnjsapi app/web.1:      throw err; 
Feb 21 01:07:39 cdnjsapi app/web.1:      ^ 
Feb 21 01:07:39 cdnjsapi app/web.1:  Error: Cannot find module 'lodash/lang/cloneDeep' 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Function.Module._resolveFilename (module.js:325:15) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Function.Module._load (module.js:276:25) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Function.cls_wrapMethod [as _load] (/app/node_modules/newrelic/lib/shimmer.js:230:38) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Module.require (module.js:353:17) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at require (internal/module.js:12:17) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at algoliasearch (/app/node_modules/algoliasearch/src/server/builds/node.js:31:19) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Object.<anonymous> (/app/apiServer.js:41:20) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Module._compile (module.js:409:26) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Object.Module._extensions..js (module.js:416:10) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Module.load (module.js:343:32) 
Feb 21 01:07:39 cdnjsapi heroku/web.1:  State changed from starting to crashed 
```

**Comment by PeterDaveHello** [comment]
@redox have you received any error like this before?
```
Feb 21 01:07:39 cdnjsapi app/web.1:  Error: Cannot find module 'lodash/lang/cloneDeep' 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Function.Module._resolveFilename (module.js:325:15) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Function.Module._load (module.js:276:25) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Function.cls_wrapMethod [as _load] (/app/node_modules/newrelic/lib/shimmer.js:230:38) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Module.require (module.js:353:17) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at require (internal/module.js:12:17) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at algoliasearch (/app/node_modules/algoliasearch/src/server/builds/node.js:31:19) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Object.<anonymous> (/app/apiServer.js:41:20) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Module._compile (module.js:409:26) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Object.Module._extensions..js (module.js:416:10) 
Feb 21 01:07:39 cdnjsapi app/web.1:      at Module.load (module.js:343:32) 
```

**Comment by IonicaBizau** [comment]
@PeterDaveHello Not sure if it helps, but why don't you require [`lodash.clonedeep`](https://www.npmjs.com/package/lodash.clonedeep) directly?

**Comment by PeterDaveHello** [comment]
@IonicaBizau Nope we don't, it's from algoliasearch.

**Comment by PeterDaveHello** [comment]
Won't it be a little bit strange to add a dependency for the dependency @IonicaBizau ?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Ah, I missed the context. :grin:

**Comment by PeterDaveHello** [comment]
@IonicaBizau do you have any idea about this? algoliasearch search has its own dependencies with lodash v3.10.1, I have no idea why the app crashed by that. Does heroku suck?

**Comment by IonicaBizau** [comment]
@PeterDaveHello The error simply says that `lodash/lang/cloneDeep.js` is missing. Make sure you have a file there.

**Comment by PeterDaveHello** [comment]
@IonicaBizau yes, in the algoliasearch's node_module, there is the file, i have no problem locally lol ...

**Comment by PeterDaveHello** [comment]
I opened an issue on heroku and shared with @ryankirkman and @thomasdavis

**Comment by PeterDaveHello** [comment]
It works well now after I disabled the cache on heroku :cry:

**Comment by ryankirkman** [comment]
@PeterDaveHello we still have a problem:

```
2016-02-22T17:15:55.337476+00:00 app[web.1]: TypeError: _.findWhere is not a function
2016-02-22T17:15:55.337480+00:00 app[web.1]:     at libraryResponse (/app/webServer.js:225:15)
2016-02-22T17:15:55.337482+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-02-22T17:15:55.337483+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-02-22T17:15:55.337484+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-02-22T17:15:55.337485+00:00 app[web.1]:     at dispatch (eval at wrapHandle (/app/node_modules/newrelic/lib/instrumentation/express.js:276:19), <anonymous>:12:19)
2016-02-22T17:15:55.337485+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-02-22T17:15:55.337486+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-02-22T17:15:55.337486+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:349:14)
2016-02-22T17:15:55.337487+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:365:14)
2016-02-22T17:15:55.337488+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
```

**Comment by PeterDaveHello** [comment]
@ryankirkman Should be fixed, my fault, forgot to update code at second upgrade.
