### ISSUE TITLE
Error: Cannot find module 'newrelic'

### ISSUE THREAD

**Issue by Shadowmad** [cdnjs/new-website#111]
Hello CDNJ team, 

could you please assist. When I am trying to start out server on Ubuntu 15.04 trough ./webServer.js
`module.js:327
    throw err;
    ^

Error: Cannot find module 'newrelic'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shadowmad/webDev/new-website/webServer.js:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)`

How I can fix that? Is it me or js app? 

Thank you!

**Comment by Shadowmad** [comment]
Please close the issue, as I fixed everything. It was on my side. 

Solution that I came up with, was npm ls to see which dependencies were absent and later sudo npm install. 

Thank you, all works.
